[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 30

[env]
NODE_ENV = "production"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"